GestionEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('registro/', include('registro.urls')),
    path('panel/', include('panel.urls')),
    path('axe/', include('django_axe.urls')),

]

panel/urls.py
from django.urls import path
from . import views

app_name = 'panel'

urlpatterns = [
    path('', views.panel, name='panel'),
    path('tabla/?page=1', views.tabla, name='tabla'),
    path('eliminar/<int:delete>/', views.eliminar, name='eliminar'),
    path('datos/<int:pk>/', views.datos, name='datos'),
    path('editar_carga/<int:pk>/', views.editar_carga, name='editar_carga'),
    path('editar_contacto/<int:pk>/', views.editar_contacto, name='editar_contacto'),
    path('eliminar_carga/<int:pk>/', views.eliminar_carga, name='eliminar_carga'),
    path('eliminar_contacto/<int:pk>/', views.eliminar_contacto, name='eliminar_contacto'),
    path('agregar_carga_familiar/', views.agregar_carga_familiar, name='agregar_carga_familiar'),
    path('agregar_contacto_emergencia/', views.agregar_contacto_emergencia, name='agregar_contacto_emergencia'),
    path('cambiar_contraseña/', views.cambiar_contraseña, name='cambiar_contraseña')
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('bloqueo/', views.bloqueo, name='bloqueo'),

]

templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Gestion empleados{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
<nav data-bs-theme="dark" class="navbar navbar-expand-lg w-100">
  <div class="container">
    <button class="navbar-toggler button-nav" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <button id="theme-toggle" aria-label="boton para cambiar entre modo oscuro y claro" style="border: none; background: none;">
            <div id="iconos-modo"> </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn" id="btnMenos">A-</button>
        </li>
        <li class="nav-item">
          <button class="btn" id="btnMas">A+</button>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'panel:panel' %}">Bienvenido 
            {% if request.user.trabajador.persona_fk != '' %}
              {{request.user.trabajador.persona_fk.nombres}}
            {% else %}
              Admin
            {% endif %}
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>

  <!-- <button id="theme-toggle" style="position: fixed; right: 0; bottom: 0;background: none; border: none; margin: 20px;">
    <div id="iconos-modo">
    </div>
  </button> -->

  <svg id="sol" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-sun"
   style="display: none" viewBox="0 0 16 16">
    <path
      d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6m0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708" />
  </svg>
  <svg id="luna"style="display: none" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
    class="bi bi-moon" viewBox="0 0 16 16">
    <path
      d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278M4.858 1.311A7.27 7.27 0 0 0 1.025 7.71c0 4.02 3.279 7.276 7.319 7.276a7.32 7.32 0 0 0 5.205-2.162q-.506.063-1.029.063c-4.61 0-8.343-3.714-8.343-8.29 0-1.167.242-2.278.681-3.286" />
  </svg>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
    integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/modos.js' %}"></script>

</body>

</html>