GestionEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('registro/', include('registro.urls')),
    path('panel/', include('panel.urls')),
    path('axe/', include('django_axe.urls')),

]

panel/urls.py
from django.urls import path
from . import views

app_name = 'panel'

urlpatterns = [
    path('', views.panel, name='panel'),
    path('tabla/?page=1', views.tabla, name='tabla'),
    path('eliminar/<int:delete>/', views.eliminar, name='eliminar'),
    path('datos/<int:pk>/', views.datos, name='datos'),
    path('editar_carga/<int:pk>/', views.editar_carga, name='editar_carga'),
    path('editar_contacto/<int:pk>/', views.editar_contacto, name='editar_contacto'),
    path('eliminar_carga/<int:pk>/', views.eliminar_carga, name='eliminar_carga'),
    path('eliminar_contacto/<int:pk>/', views.eliminar_contacto, name='eliminar_contacto'),
    path('agregar_carga_familiar/', views.agregar_carga_familiar, name='agregar_carga_familiar'),
    path('agregar_contacto_emergencia/', views.agregar_contacto_emergencia, name='agregar_contacto_emergencia'),
    path('cambiar_contraseña/', views.cambiar_contraseña, name='cambiar_contraseña')
]

registro/urls.py
from django.urls import path
from . import views

app_name = 'registro'  

urlpatterns = [
    path('datos_personales/', views.vistaDatosPersonales, name='vistaDatosPersonales'),
    path('datos_laborales/', views.vistaDatosLaborales, name='vistaDatosLaborales'),
    path('contacto_emergencia/', views.vistaContactoEmergencia, name='vistaContactoEmergencia'),
    path('carga_familiar/', views.vistaCargaFamiliar, name='vistaCargaFamiliar'),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('bloqueo/', views.bloqueo, name='bloqueo'),

]

panel/models.py
from django.db import models

# Create your models here.

registro/models.py
from django.db import models
from django.contrib.auth.models import User



class Area(models.Model):
    Areas = (
        ('Area1','Area1'),
        ('Area2','Area2'),
    )
    nombre_area = models.CharField(max_length=30, choices=Areas)

    def __str__(self):
        return self.nombre_area


class Departamento(models.Model):
    Departamentos = (
        ('Departamento1','Departamento1'),
        ('Departamento2','Departamento2'),
        ('Departamento3','Departamento3'),
        ('Departamento4','Departamento4'),
    )
    nombre_departamento = models.CharField(max_length=30, choices=Departamentos)
    area_fk = models.ForeignKey(Area, models.CASCADE)

    def __str__(self):
        return self.nombre_departamento


class Cargo(models.Model):
    Cargos = (
        ('Jefe RR.HH', 'Jefe RR.HH'),
        ('Personal RR.HH', 'Personal RR.HH'),
        ('Trabajador', 'Trabajador'),
    )
    nombre_cargo = models.CharField(max_length=30, choices=Cargos)

    def __str__(self):
        return self.nombre_cargo



class Persona(models.Model):
    Sexo = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
    )
    nombres = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=20)
    apellido_materno = models.CharField(max_length=20)
    rut = models.CharField(max_length=12)
    sexo = models.CharField(max_length=30, choices=Sexo)
    direccion = models.CharField(max_length=50)
    telefono = models.CharField(max_length=15)




class Trabajador(models.Model):
    persona_fk = models.OneToOneField(Persona,on_delete=models.CASCADE)
    fecha_ingreso = models.DateField(null=True)
    contraseña_cambiada = models.BooleanField(default=False)
    cargo_fk = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    departamento_fk = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    user_fk = models.OneToOneField(User, on_delete=models.CASCADE)


class ContactoEmergencia(models.Model):
    Relaciones = (
        ('Padre', 'Padre'),
        ('Madre', 'Madre'),
        ('Hijo', 'Hijo'),
        ('Hija', 'Hija'),
        ('Esposo', 'Esposo'),
        ('Esposa', 'Esposa'),
        ('Hermano', 'Hermano'),
        ('Hermana', 'Hermana'),
        ('Abuelo', 'Abuelo'),
        ('Abuela', 'Abuela'),
        ('Nieto', 'Nieto'),
        ('Nieta', 'Nieta'),
        ('Tío', 'Tío'),
        ('Tía', 'Tía'),
        ('Sobrino', 'Sobrino'),
        ('Sobrina', 'Sobrina'),
        ('Primo', 'Primo'),
        ('Prima', 'Prima'),
        ('Otro', 'Otro'),
        
    )

    nombre = models.CharField(max_length=30)
    relacion = models.CharField(max_length=20, choices=Relaciones)
    telefono = models.CharField(max_length=15)
    trabajador_fk =models.ForeignKey(Trabajador, on_delete=models.CASCADE)



class CargaFamiliar(models.Model):
    Parentescos = (
        ('Padre', 'Padre'),
        ('Madre', 'Madre'),
        ('Hijo', 'Hijo'),
        ('Hija', 'Hija'),
        ('Esposo', 'Esposo'),
        ('Esposa', 'Esposa'),
        ('Hermano', 'Hermano'),
        ('Hermana', 'Hermana'),
        ('Abuelo', 'Abuelo'),
        ('Abuela', 'Abuela'),
        ('Nieto', 'Nieto'),
        ('Nieta', 'Nieta'),
        ('Tío', 'Tío'),
        ('Tía', 'Tía'),
        ('Sobrino', 'Sobrino'),
        ('Sobrina', 'Sobrina'),
        ('Primo', 'Primo'),
        ('Prima', 'Prima'),
        ('Otro', 'Otro'),
    )
    Sexo = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
    )
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=30)
    sexo = models.CharField(max_length=30, choices=Sexo)
    parentesco = models.CharField(max_length=20, choices=Parentescos)
    trabajador_fk =models.ForeignKey(Trabajador, on_delete=models.CASCADE)

panel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from registro.models import Trabajador, Persona, CargaFamiliar, ContactoEmergencia
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import F
from django.contrib.auth.decorators import login_required
from registro.forms import FormularioDatosPersonales, FormularioCargaFamiliar, FormularioContactoEmergencia, FormularioContraseña, FormularioDatosLaborales
from django.contrib.auth import update_session_auth_hash


# Create your views here.
@login_required
def panel(request):
    if request.user.is_authenticated :
        try:
            trabajador = request.user.trabajador
        except:
            return render(request, 'panel/panel.html')        
        return render(request, 'panel/panel.html', {'trabajador': trabajador})

    else:
        return redirect('usuarios:login')
    
@login_required
def tabla(request):
    
    order = request.GET.get('order', 'persona_fk__rut')
    query = request.GET.get('search', '')

    trabajadores = Trabajador.objects.all()

    if query:
        trabajadores = trabajadores.filter(
            Q(persona_fk__nombres__icontains=query) |
            Q(persona_fk__apellido_paterno__icontains=query) |
            Q(persona_fk__apellido_materno__icontains=query) |
            Q(cargo_fk__nombre_cargo__icontains=query) |
            Q(persona_fk__sexo__icontains=query)
        )

    trabajadores = trabajadores.order_by(order)

    paginator = Paginator(trabajadores, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'panel/tabla_trabajadores.html', {'page_obj': page_obj, 'query': query})

@login_required
def eliminar(request, delete):
    if delete:
        trabajador = get_object_or_404(Trabajador, pk=delete)
        trabajador.delete()
        messages.success(request, 'Trabajador eliminado correctamente')
    
    return redirect('panel:tabla')


@login_required
def datos(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    if request.user.trabajador.persona_fk.pk == persona.pk:
        cargasF = CargaFamiliar.objects.filter(trabajador_fk = request.user.trabajador)
        contactoE = ContactoEmergencia.objects.filter(trabajador_fk = request.user.trabajador)
        if request.method == 'POST':
            form = FormularioDatosPersonales(request.POST,  instance=persona, skip_rut_validation=True)
            if form.is_valid():
                form.save()
                form = FormularioDatosPersonales(instance=persona)
                messages.success(request, 'Datos personales actualizados correctamente.')
                return redirect('panel:panel')
            else:
                form = FormularioDatosPersonales(instance=persona)
                return render(request, 'panel/datos.html', {'form': form, 'cargasF': cargasF, 'contactoE': contactoE})

        else:
            form = FormularioDatosPersonales(instance=persona)
            return render(request, 'panel/datos.html', {'form': form, 'cargasF': cargasF, 'contactoE': contactoE })
    else:
        messages.error(request, 'No puede acceder a informacion que no está asociada a su cuenta')
        return redirect('usuarios:login')


@login_required
def editar_carga(request, pk):
    carga = get_object_or_404(CargaFamiliar, pk=pk)
    if request.user.trabajador == carga.trabajador_fk:
        if request.method == 'POST':
            formC = FormularioCargaFamiliar(request.POST, instance=carga)
            if formC.is_valid():
                formC.save()
                return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
        else:
            formC = FormularioCargaFamiliar(instance=carga)
            return render(request, 'panel/editar_carga.html', {'formC': formC})
    else:
        messages.error(request, 'No puede editar una carga familiar que no está asociada a su cuenta')
        return redirect('panel:panel')
    
@login_required
def editar_contacto(request, pk):
    contacto = get_object_or_404(ContactoEmergencia, pk=pk)
    if request.user.trabajador == contacto.trabajador_fk:
        if request.method == 'POST':
            formE = FormularioContactoEmergencia(request.POST, instance=contacto)
            if formE.is_valid():
                formE.save()
                return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
        else:
            formE = FormularioContactoEmergencia(instance=contacto)
            return render(request, 'panel/editar_contacto.html', {'formE': formE})
    else:
        messages.error(request, 'No puede editar un contacto que no está asociado a su cuenta')
        return redirect('panel:panel')
    
@login_required
def agregar_carga_familiar(request):
    cargas = CargaFamiliar.objects.filter(trabajador_fk = request.user.trabajador)
    if cargas.count() >= 5:
        messages.warning(request, 'No se pueden agregar más de 5 cargas familiares.')
        return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
    else:
        if request.method == 'GET':
            form = FormularioCargaFamiliar()
            return render(request, 'registro/formulario_carga_familiar.html', {'form': form})
        else:
            form = FormularioCargaFamiliar(request.POST)
            cargas = CargaFamiliar.objects.filter(trabajador_fk = request.user.trabajador)
            if form.is_valid():
                if cargas.filter(rut=form.cleaned_data['rut']).exists():
                    messages.warning(request, 'Ya existe una carga familiar con ese RUT.')
                    return render(request, 'registro/formulario_carga_familiar.html', {'form': form})
                else:
                    trabajador = request.user.trabajador
                    print(form.cleaned_data)
                    carga = CargaFamiliar.objects.create(
                        **form.cleaned_data,
                        trabajador_fk= trabajador
                    )
                    messages.success(request, 'Se agrego correctamente la carga familiar')
                return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
            else:
                return render(request, 'registro/formulario_carga_familiar.html', {'form': form})
        
@login_required
def agregar_contacto_emergencia(request):
    contactos = ContactoEmergencia.objects.filter(trabajador_fk = request.user.trabajador)
    if contactos.count() >= 3:
        messages.warning(request, 'No se pueden agregar más de 3 contactos de emergencia.')
        return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
    else:
        if request.method == 'GET':
            form = FormularioContactoEmergencia()
            return render(request, 'registro/formulario_contacto_emergencia.html', {'form': form})
        else:
            form = FormularioContactoEmergencia(request.POST)
            if form.is_valid():
                trabajador = request.user.trabajador
                print(form.cleaned_data)
                contacto = ContactoEmergencia.objects.create(
                    **form.cleaned_data,
                    trabajador_fk= trabajador
                )
                messages.success(request, 'Se agrego correctamente el contacto de emergencia')
                return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)
            else:
                return render(request, 'registro/formulario_contacto_emergencia.html', {'form': form})
        

        
@login_required
def eliminar_carga(request, pk):
    carga = get_object_or_404(CargaFamiliar, pk=pk)
    carga.delete()
    messages.success(request, 'Carga familiar eliminada correctamente.')
    return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)

@login_required
def eliminar_contacto(request, pk):
    contacto = get_object_or_404(ContactoEmergencia, pk=pk)
    contacto.delete()
    messages.success(request, 'Contacto de emergencia eliminado correctamente.')
    return redirect('panel:datos', pk=request.user.trabajador.persona_fk.pk)


def cambiar_contraseña(request):
    if request.method == 'POST':
        form = FormularioContraseña(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            messages.success(request, 'La contraseña se cambió correctamente')
            return redirect('panel:panel')
        else:
            messages.error(request, 'Por favor corrija los errores')
    else:
        form = FormularioContraseña(request.user)
    return render(request, 'panel/cambiar_contraseña.html', {'form': form})

panel/templates/panel/cambiar_contraseña.html
{% extends 'base.html' %}

{% block title %}Cambiar contraseña{% endblock %}

{% block content %}
<div class="container mt-5 pseudofondo"
    style="display: flex; justify-content: center; flex-direction: column; max-width: 500px; border-radius: 10px;padding: 30px;">
    <h2>Cambiar contraseña</h2>
    <form method="post" style="display: flex; flex-direction: column; gap: 5px; margin-top: 20px;">
        {% csrf_token %}
        {{form}}
       <button class="btn btn-primary mt-3">Guardar</button>
    </form>
</form>
{% if messages %}
{% for message in messages %}
<div class="alert {{message.tags}} alert-dismissible fade show mt-3" style="font-size: 13px;" role="alert" >
{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}

{% endif %}
</div>
{% endblock %}

panel/templates/panel/datos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Mis datos{% endblock %}

{% block content %}
<h1 class="mb-2">Mis datos</h1>
<div style="display: grid; grid-template-columns: 45% 45%; justify-content: space-between;">
    <section >
        <h2>Datos personales</h2>
        <form  class="edit" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_rut">RUT</label>
                <input type="text" name="rut" id="id_rut" value="{{ form.rut.value }}" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="id_nombres">Nombres</label>
                <input type="text" name="nombres" id="id_nombres" value="{{ form.nombres.value }}" class="form-control" >
            </div>
            <div class="form-group">
                <label for="id_apellido_paterno">Apellido Paterno</label>
                <input type="text" name="apellido_paterno" id="id_apellido_paterno" value="{{ form.apellido_paterno.value }}" class="form-control" >
            </div>
            <div class="form-group">
                <label for="id_apellido_materno">Apellido Materno</label>
                <input type="text" name="apellido_materno" id="id_apellido_materno" value="{{ form.apellido_materno.value }}" class="form-control" >
            </div>
            <div class="form-group">
                <label for="id_sexo">Sexo</label>
                <input type="text" name="sexo" id="id_sexo" value="{{ form.sexo.value }}" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="id_direccion">Direccion</label>
                {{form.direccion}}
            </div>
            <div class="form-group">
                <label for="id_telefono">Telefono</label>
                {{form.telefono}}
            </div>
            <button type="submit" class="btn btn-primary mt-4">Guardar cambios</button>
        </form>
        {% if messages %}
        {% for message in messages %}
        <div class="alert {{message.tags}} alert-dismissible fade show mt-3" style="font-size: 13px;" role="alert" >
        {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
    
    {% endif %}
    </section>
    <section id="datosLaborales">
        <h2 >Datos laborales</h2>
        <div class="form-group">
            <label for="cargo">Cargo</label>
            <input style="cursor: not-allowed;"  id="cargo" type="text"  value="{{ request.user.trabajador.cargo_fk }}" class="form-control" readonly>
        </div>
        <div class="form-group">
            <label for="area">Area</label>
            <input style="cursor: not-allowed;"  id="area"  type="text"  value="{{ request.user.trabajador.departamento_fk.area_fk}}" class="form-control" readonly>
            
        </div>
        <div class="form-group">
            <label for="departamento">Departamento</label>
            <input style="cursor: not-allowed;"  type="text" id="departamento" value="{{ request.user.trabajador.departamento_fk }}" class="form-control" readonly>
        </div>
        <div class="form-group">
            <label for="fechaI">Fecha de ingreso</label>
            <input style="cursor: not-allowed;" id="fechaI" type="text"  value="{{ request.user.trabajador.fecha_ingreso }}" class="form-control" readonly>
        </div>
    </section>
</div>
<hr>
<div style="display: grid; grid-template-columns: 45% 45%; justify-content: space-between;">
    <section >
        <div style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center;">
            <h2>Cargas familiares</h2>
            <p style="margin: 0;">

                <a href="{% url 'panel:agregar_carga_familiar' %}" class="btn btn-success btn-sm">Agregar</a>
            </p style="margin: 0;">
        </div>
        <div class="table-responsive">
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>RUT</th>
                        <th>Nombre</th>
                        <th>Parentesco</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for carga in cargasF %}
                    <tr>
                        <td>{{carga.rut}}</td>
                        <td>{{carga.nombre}}</td>
                        <td>{{carga.parentesco}}</td>
                        <td>
                            <a href="{% url 'panel:editar_carga' carga.pk %}" class="btn btn-primary btn-sm">Editar</a>
                            <a class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#modal{{carga.pk}}">Eliminar</a>
                        </td>
                    </tr>
                    <div class="modal fade" id="modal{{carga.pk}}"  data-bs-backdrop="static"  data-bs-keyboard="false" tabindex="-1">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h3 class="modal-title">Advertencia</h3>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <p>¿Está seguro de  eliminar la carga familiar {{carga.nombre}}?</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                              <a type="a" class="btn btn-danger" href="{% url 'panel:eliminar_carga' carga.pk %}">Eliminar</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </section>
    <section >
        <div style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center;">
            <h2>Contactos emergencia</h2>
            <p style="margin: 0;">

                <a href="{% url 'panel:agregar_contacto_emergencia' %}" class="btn btn-success btn-sm">Agregar</a>
            </p style="margin: 0;">
        </div>
        <div class="table-responsive">
            <table class="table mt-3" >
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Telefono</th>
                        <th>Relacion</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contacto in contactoE %}
                    <tr>
                        <td>{{contacto.nombre}}</td>
                        <td>{{contacto.telefono}}</td>
                        <td>{{contacto.relacion}}</td>
                        <td>
                            <a href="{% url 'panel:editar_contacto' contacto.pk %}" class="btn btn-primary btn-sm">Editar</a>
                            <a class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#modalC{{contacto.pk}}">Eliminar</a>
                        </td>
                    </tr>
                    <div class="modal fade" id="modalC{{contacto.pk}}"  data-bs-backdrop="static"  data-bs-keyboard="false" tabindex="-1">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h3 class="modal-title">Advertencia</h3>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <p>¿Está seguro de  eliminar el contacto de emergencia {{contacto.nombre}}?</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                              <a type="a" class="btn btn-danger" href="{% url 'panel:eliminar_contacto' contacto.pk %}">Eliminar</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </section>
</div>
{% endblock %}

panel/templates/panel/editar_carga.html
{% extends 'base.html' %}

{% block title %}Editar carga familiar{% endblock %}
{% block content %}

<h1>Editar carga familiar</h1>

<form method="post" class="edit">
    {% csrf_token %}
   
        <div class="form-group">
            <label for="id_rut">RUT</label>
            <input type="text" name="rut" id="id_rut" value="{{ formC.rut.value }}" class="form-control" readonly>
        </div>
        <div class="form-group">
            <label for="id_nombres">Nombre</label>
            {{formC.nombre}}
        </div>
        <div class="form-group">
            <label for="id_sexo">Sexo</label>
                {{formC.sexo}}
        </div>
        <div class="form-group">
            <label for="id_parentesco">Parentesco</label>
            {{formC.parentesco}}
        </div>
        <button type="submit" class="btn btn-success mt-3">Guardar cambios</button>

</form>

{% endblock %}

panel/templates/panel/editar_contacto.html
{% extends 'base.html' %}

{% block title %}Editar contacto emergencia{% endblock %}
{% block content %}

<h1>Editar contacto emergencia</h1>

<form method="post">
    {% csrf_token %}
   
        <div class="form-group">
            <label for="id_nombres">Nombre</label>
            {{formE.nombre}}
        </div>
        <div class="form-group">
            <label for="id_relacion">Relacion</label>
                {{formE.relacion}}
        </div>
        <div class="form-group">
            <label for="id_telefono">Telefono</label>
            {{formE.telefono}}
        </div>
        <button type="submit" class="btn btn-success mt-3">Guardar cambios</button>

</form>

{% endblock %}

panel/templates/panel/panel.html
{% extends 'base.html' %}

{% block title %}Panel{% endblock %}

{% block content %}

<h1 style='text-align: center;'>EL CORREO DE YURY</h1>
{% if trabajador %}
<div style="display: grid; gap: 10px; grid-template-columns: repeat(3, 3fr);grid-template-rows: 50px 50px; padding: 30px 0px; justify-content: space-between;">
    {% if request.user.trabajador.cargo_fk.nombre_cargo == 'Personal RR.HH' or request.user.trabajador.cargo_fk.nombre_cargo == 'Jefe RR.HH' %}
    <a href="{% url 'registro:vistaDatosPersonales' %}" class="btn btn-primary">Crear ficha</a>
    <a href="{% url 'panel:tabla' %}" class="btn btn-primary">Resumen trabajadores</a>
    {% endif %}
    <a href="{% url 'panel:datos' trabajador.persona_fk.pk %}" class="btn btn-primary">Ver mis datos</a>
    <a href="{% url 'panel:cambiar_contraseña' %}" class="btn btn-primary">Cambiar contraseña</a>
    <a href="{% url 'usuarios:logout' %}" class="btn btn-primary">Cerrar Sesión</a>
</div>
{%else %}
<div style="display: grid; gap: 10px; grid-template-columns: repeat(3, 3fr);grid-template-rows: 50px 50px; padding: 30px 0px; justify-content: space-between;">

<a href="{% url 'registro:vistaDatosPersonales' %}" class="btn btn-primary">Crear ficha</a>
<a href="{% url 'panel:tabla' %}" class="btn btn-primary">Resumen trabajadores</a>
<a href="{% url 'usuarios:logout' %}" class="btn btn-primary">Cerrar Sesión</a>
</div>

{% endif %}


{% if messages %}
    {% for message in messages %}
    <div class="alert {{message.tags}} alert-dismissible fade show mt-3" style="font-size: 13px;" role="alert" >
    {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}

{% endif %}



{% endblock %}